version: 2
updates:
  - package-ecosystem: gomod
    directory: /check-git-repos-source
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /pause-source
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /check-git-branch-source
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
