#!/usr/bin/env python3
"""Generate a Homebrew cask for one tool in this repo and write it into a tap clone.

The four per-tool release workflows each used to embed their own copy of a
formula generator that regex-patched the existing Ruby in place. That was
fragile — a formula whose layout drifted stopped being patched correctly and
failed silently, shipping a cask that still pointed at the previous release.
This writes the whole file every time instead, so the output is a pure function
of the checksums and the tag.

The output deliberately mirrors what GoReleaser's `homebrew_casks` emits for the
standalone Go repos, so every cask in kevinpinscoe/homebrew-tap reads the same
regardless of which pipeline produced it.

Usage:
    python3 .github/homebrew-cask.py \
        --tool menu-app \
        --version 2.0.1 \
        --tag menu-app-v2.0.1 \
        --desc "Run repository scripts from a simple TUI menu"

Run it from the directory holding checksums.txt (the tool's *-source directory).
"""

import argparse
import pathlib
import sys

REPO = "kevinpinscoe/tools"

# Homebrew's on_* selector for each binary we publish. Order matters only for
# readability of the generated file.
TARGETS = [
    ("macos", "arm", "darwin-arm64"),
    ("linux", "intel", "linux-amd64"),
    ("linux", "arm", "linux-arm64"),
]


def ruby_string(value):
    """Escape a Python string for interpolation into a double-quoted Ruby literal."""
    return value.replace("\\", "\\\\").replace('"', '\\"')


def read_checksums(path):
    """Parse a sha256sum(1) output file into {filename: sha}."""
    checksums = {}
    for line in pathlib.Path(path).read_text().splitlines():
        if not line.strip():
            continue
        sha, _, fname = line.partition("  ")
        checksums[fname.strip()] = sha.strip()
    return checksums


def arch_block(tool, tag, suffix, sha, indent):
    """Render the sha256/url/binary trio for one architecture."""
    pad = " " * indent
    artifact = f"{tool}-{suffix}"
    url = f"https://github.com/{REPO}/releases/download/{tag}/{artifact}"
    return (
        f'{pad}sha256 "{sha}"\n'
        f'{pad}url "{url}"\n'
        f'{pad}binary "{artifact}", target: "{ruby_string(tool)}"\n'
    )


def render(tool, version, tag, desc, checksums):
    by_os = {}
    for os_name, cpu, suffix in TARGETS:
        artifact = f"{tool}-{suffix}"
        if artifact not in checksums:
            raise SystemExit(
                f"error: {artifact} is missing from the checksums file — "
                f"the build step and this generator disagree on what gets published"
            )
        by_os.setdefault(os_name, []).append((cpu, suffix, checksums[artifact]))

    out = [
        "# This file was generated by .github/homebrew-cask.py. DO NOT EDIT.",
        f'cask "{ruby_string(tool)}" do',
        f'  version "{ruby_string(version)}"',
        "",
    ]

    for os_name in ("macos", "linux"):
        out.append(f"  on_{os_name} do")
        for cpu, suffix, sha in by_os.get(os_name, []):
            out.append(f"    on_{cpu} do")
            out.append(arch_block(tool, tag, suffix, sha, indent=6).rstrip("\n"))
            out.append("    end")
        out.append("  end")
        out.append("")

    out += [
        f'  name "{ruby_string(tool)}"',
        f'  desc "{ruby_string(desc)}"',
        f'  homepage "https://github.com/{REPO}"',
        "",
        "  livecheck do",
        '    skip "Auto-generated on release."',
        "  end",
        "end",
    ]
    return "\n".join(out) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--tool", required=True, help="tool and cask name, e.g. menu-app")
    parser.add_argument("--version", required=True, help="bare version, e.g. 2.0.1")
    parser.add_argument("--tag", required=True, help="release tag, e.g. menu-app-v2.0.1")
    parser.add_argument("--desc", required=True, help="one-line description for the cask")
    parser.add_argument("--tap", default="/tmp/homebrew-tap", help="path to the tap clone")
    parser.add_argument("--checksums", default="checksums.txt", help="sha256sum output file")
    args = parser.parse_args()

    checksums = read_checksums(args.checksums)
    cask = render(args.tool, args.version, args.tag, args.desc, checksums)

    casks_dir = pathlib.Path(args.tap) / "Casks"
    casks_dir.mkdir(parents=True, exist_ok=True)
    out_path = casks_dir / f"{args.tool}.rb"
    out_path.write_text(cask)
    print(f"wrote {out_path}", file=sys.stderr)


if __name__ == "__main__":
    main()
